name: Automated Preprocessing

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  preprocess-data:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install -- upgrade pip
          pip installpandas numpy scikit-learn joblib

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Hafsyah_Huzaifah.py

      - name: Move processed data
        run: |
          mv train_pca.csv preprocessing/
          mv test_pca.csv preprocessing/

      - name: Commit processed data
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.emsil }}
          git add preprocessing/train_pca.csv preprocessing/test_pca.csv
          git commit -m 'Berhasil update dataset' || echo 'Tidak berhasil mengunggah dataset terbaru'
          git push
